'use client';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Bookmark, Check, Compass, Heart, LayoutGrid, Menu, Plus, Search, Sparkles, WandSparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

type Item = { id:number; title:string; maker:string; category:string; image:string; type:string; likes:string };
type Project = { id:number; title:string; description:string; tags:string[]; published:boolean; date:string };
type ModelTool = { name:string; title:string; description:string; inputSchema:object; annotations:object; execute:(input:unknown)=>unknown };
declare global { interface Document { modelContext?: { registerTool:(tool:ModelTool, options?:{signal:AbortSignal})=>void|Promise<void> } } }
const items:Item[] = [
 {id:1,title:'AI로 만드는 키네틱 타이포그래피',maker:'민아 · Motion Designer',category:'튜토리얼',type:'12분 읽기',likes:'1.2k',image:'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=1200&q=85'},
 {id:2,title:'브랜드 세계관을 확장하는 이미지 모델',maker:'Studio Namu',category:'케이스 스터디',type:'프로젝트',likes:'864',image:'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1200&q=85'},
 {id:3,title:'감각적인 3D 오브젝트 프롬프트 30',maker:'Juno Park',category:'리소스',type:'프롬프트',likes:'2.4k',image:'https://images.unsplash.com/photo-1634986666676-ec8fd927c23d?auto=format&fit=crop&w=1200&q=85'},
 {id:4,title:'생성형 AI 시대의 편집 디자인',maker:'Paperlab',category:'인사이트',type:'8분 읽기',likes:'739',image:'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=85'},
 {id:5,title:'인터랙티브 포스터 실험실',maker:'Seoul Type Club',category:'케이스 스터디',type:'프로젝트',likes:'1.8k',image:'https://images.unsplash.com/photo-1557682250-33bd709cbe85?auto=format&fit=crop&w=1200&q=85'},
 {id:6,title:'나만의 컬러 시스템을 학습시키는 법',maker:'Haneul Kim',category:'튜토리얼',type:'15분 읽기',likes:'922',image:'https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?auto=format&fit=crop&w=1200&q=85'}
];
const cats=['전체','인사이트','튜토리얼','케이스 스터디','리소스'];

export default function Home(){
 const [tab,setTab]=useState<'discover'|'saved'|'projects'>('discover'); const [cat,setCat]=useState('전체'); const [query,setQuery]=useState('');
 const [saved,setSaved]=useState<number[]>([]); const [projects,setProjects]=useState<Project[]>([]); const [open,setOpen]=useState(false); const [idea,setIdea]=useState(''); const [draft,setDraft]=useState<Project|null>(null); const [toast,setToast]=useState(''); const [menu,setMenu]=useState(false);
 useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem('artpick:saved')||'[]'));setProjects(JSON.parse(localStorage.getItem('artpick:projects')||'[]'))}catch{}},[]);
 useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'save_artpick_content',title:'Artpick 콘텐츠 저장',description:'Artpick의 콘텐츠 ID를 저장 목록에 추가합니다.',inputSchema:{type:'object',properties:{contentId:{type:'number',minimum:1,maximum:6}},required:['contentId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const id=(input as {contentId?:number}).contentId;if(!id||!items.some(x=>x.id===id))throw new Error('유효한 콘텐츠 ID가 필요합니다.');const current: number[]=JSON.parse(localStorage.getItem('artpick:saved')||'[]');const next=current.includes(id)?current:[...current,id];localStorage.setItem('artpick:saved',JSON.stringify(next));setSaved(next);return {saved:true,contentId:id};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)};
 const nav=(t:typeof tab)=>{setTab(t);setCat('전체');setQuery('');setMenu(false)};
 const toggle=(id:number)=>{const exists=saved.includes(id);const next=exists?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem('artpick:saved',JSON.stringify(next));notify(exists?'저장에서 삭제했어요.':'콘텐츠를 저장했어요.')};
 const filtered=useMemo(()=>items.filter(x=>(cat==='전체'||x.category===cat)&&(`${x.title} ${x.maker}`).toLowerCase().includes(query.toLowerCase())&&(tab!=='saved'||saved.includes(x.id))),[cat,query,saved,tab]);
 const generate=()=>{if(!idea.trim())return;const tags=idea.split(/[ ,]+/).filter(Boolean).slice(0,3);setDraft({id:Date.now(),title:idea.length>28?idea.slice(0,28)+'…':idea,description:`관찰한 장면과 생성형 이미지를 연결해 ${tags[0]||'새로운 감각'}을 시각 언어로 탐구하는 프로젝트입니다. 반복, 대비, 우연성을 활용해 일관된 시리즈로 발전시켜 보세요.`,tags:[...tags,'AI 크리에이티브'].slice(0,4),published:false,date:new Date().toLocaleDateString('ko-KR')})};
 const saveProject=(published:boolean)=>{if(!draft)return;const next=[{...draft,published},...projects];setProjects(next);localStorage.setItem('artpick:projects',JSON.stringify(next));setOpen(false);setDraft(null);setIdea('');setTab('projects');notify(published?'프로젝트를 공개했어요!':'초안을 저장했어요.')};
 return <main className="min-h-screen bg-[#f6f5f1] text-[#181816]">
  <header className="sticky top-0 z-40 border-b border-black/8 bg-[#f6f5f1]/90 backdrop-blur-xl"><div className="mx-auto flex h-[70px] max-w-[1440px] items-center gap-5 px-5 lg:px-10">
   <button onClick={()=>nav('discover')} className="flex items-center gap-2" aria-label="Artpick 홈"><span className="grid size-8 place-items-center rounded-full bg-[#ff5c35] font-black text-white">A</span><b className="text-xl tracking-[-.05em]">artpick</b></button>
   <nav className="hidden gap-1 md:flex"><Nav active={tab==='discover'} onClick={()=>nav('discover')} icon={<Compass/>}>발견</Nav><Nav active={tab==='saved'} onClick={()=>nav('saved')} icon={<Bookmark/>}>저장</Nav><Nav active={tab==='projects'} onClick={()=>nav('projects')} icon={<LayoutGrid/>}>내 프로젝트</Nav></nav>
   <div className="relative ml-auto hidden w-full max-w-sm md:block"><Search className="absolute left-3 top-3 size-4 text-black/40"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="콘텐츠, 크리에이터 검색" className="h-10 w-full rounded-full border border-black/10 bg-white pl-10 pr-4 text-sm outline-none focus:ring-4 focus:ring-black/5"/></div>
   <Button onClick={()=>setOpen(true)} className="hidden h-10 rounded-full bg-[#181816] px-5 sm:flex"><Sparkles/>아이디어 만들기</Button><button onClick={()=>setMenu(!menu)} className="ml-auto grid size-10 place-items-center rounded-full border bg-white md:hidden" aria-label="메뉴"><Menu className="size-5"/></button>
  </div>{menu&&<div className="border-t p-4 md:hidden"><div className="mb-3 flex rounded-full border bg-white px-4"><Search className="my-auto size-4 text-black/40"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="검색" className="h-11 min-w-0 flex-1 bg-transparent px-3 outline-none"/></div><div className="grid grid-cols-3"><Nav active={tab==='discover'} onClick={()=>nav('discover')} icon={<Compass/>}>발견</Nav><Nav active={tab==='saved'} onClick={()=>nav('saved')} icon={<Bookmark/>}>저장</Nav><Nav active={tab==='projects'} onClick={()=>nav('projects')} icon={<LayoutGrid/>}>프로젝트</Nav></div></div>}</header>
  {tab!=='projects'?<><section className="mx-auto max-w-[1440px] px-5 pb-10 pt-12 lg:px-10 lg:pt-16"><div className="grid items-end gap-8 lg:grid-cols-[1fr_420px]"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-[#ff5c35]">{tab==='saved'?'Your collection':'Today’s creative signals'}</p><h1 className="text-[clamp(2.6rem,6vw,5.7rem)] font-semibold leading-[.94] tracking-[-.065em]">{tab==='saved'?<>영감을 모은<br/>나만의 서랍</>:<>발견이 아이디어가<br/>되는 순간.</>}</h1></div><div className="rounded-[28px] bg-[#d9ff53] p-7"><WandSparkles className="mb-10 size-7"/><p className="text-xl font-semibold leading-snug">떠오른 생각이 있나요?<br/>AI와 함께 프로젝트로 구체화하세요.</p><button onClick={()=>setOpen(true)} className="mt-6 flex items-center gap-2 text-sm font-bold">아이디어 시작하기 <ArrowRight className="size-4"/></button></div></div></section>
  <section className="mx-auto max-w-[1440px] px-5 pb-24 lg:px-10"><div className="mb-7 flex gap-2 overflow-x-auto pb-2">{cats.map(x=><button key={x} onClick={()=>setCat(x)} className={`shrink-0 rounded-full border px-4 py-2 text-sm font-medium ${cat===x?'border-[#181816] bg-[#181816] text-white':'border-black/10 bg-white'}`}>{x}</button>)}</div>{filtered.length?<div className="grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((x,i)=><article key={x.id} className="group"><div className={`relative overflow-hidden rounded-[24px] bg-neutral-200 ${i%3===1?'aspect-[4/5]':'aspect-[4/3]'}`}><img src={x.image} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1.5 text-xs font-semibold">{x.category}</span><button onClick={()=>toggle(x.id)} aria-label={saved.includes(x.id)?'저장 취소':'저장'} className={`absolute right-4 top-4 grid size-10 place-items-center rounded-full shadow ${saved.includes(x.id)?'bg-[#ff5c35] text-white':'bg-white/90'}`}><Bookmark className={`size-4 ${saved.includes(x.id)?'fill-current':''}`}/></button></div><div className="pt-4"><div className="flex justify-between text-xs text-black/45"><span>{x.type}</span><span className="flex items-center gap-1"><Heart className="size-3"/>{x.likes}</span></div><h2 className="mt-2 text-xl font-semibold tracking-tight">{x.title}</h2><p className="mt-1 text-sm text-black/55">{x.maker}</p></div></article>)}</div>:<Empty onClick={()=>nav('discover')}/>}</section></>
  :<section className="mx-auto max-w-[1200px] px-5 py-12 lg:px-10 lg:py-16"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-[#ff5c35]">My studio</p><h1 className="text-5xl font-semibold tracking-[-.055em] sm:text-7xl">내 프로젝트</h1><p className="mt-4 text-black/55">아이디어를 다듬고, 준비되면 세상에 공개하세요.</p></div><Button onClick={()=>setOpen(true)} className="h-11 rounded-full px-5"><Plus/>새 프로젝트</Button></div>{projects.length?<div className="mt-12 grid gap-5 sm:grid-cols-2">{projects.map((p,i)=><article key={p.id} className={`rounded-[28px] p-7 ${i%2?'bg-[#c8b8ff]':'bg-white'}`}><div className="mb-16 flex justify-between"><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${p.published?'bg-black text-white':'bg-white/70'}`}>{p.published?'공개됨':'초안'}</span><span className="text-xs text-black/45">{p.date}</span></div><h2 className="text-2xl font-semibold">{p.title}</h2><p className="mt-3 text-sm leading-relaxed text-black/60">{p.description}</p><div className="mt-5 flex flex-wrap gap-2">{p.tags.map(t=><span key={t} className="rounded-full border border-black/10 px-2.5 py-1 text-xs">#{t}</span>)}</div></article>)}</div>:<div className="mt-12 rounded-[32px] border border-dashed border-black/15 py-20 text-center"><Sparkles className="mx-auto mb-5 size-8 text-[#ff5c35]"/><h2 className="text-2xl font-semibold">첫 아이디어를 프로젝트로 만들어 보세요</h2><p className="mt-2 text-sm text-black/50">한 문장만 입력하면 AI가 시작점을 제안해요.</p><Button onClick={()=>setOpen(true)} className="mt-6 rounded-full">시작하기</Button></div>}</section>}
  <button onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-30 flex h-14 items-center gap-2 rounded-full bg-[#ff5c35] px-5 font-semibold text-white shadow-xl sm:hidden"><Sparkles className="size-5"/>아이디어</button>{toast&&<div role="status" className="fixed bottom-6 left-1/2 z-[70] flex -translate-x-1/2 items-center gap-2 whitespace-nowrap rounded-full bg-black px-5 py-3 text-sm text-white"><Check className="size-4 text-[#d9ff53]"/>{toast}</div>}
  <Dialog open={open} onOpenChange={v=>{setOpen(v);if(!v)setDraft(null)}}><DialogContent className="max-w-2xl overflow-hidden rounded-[28px] p-0 sm:max-w-2xl"><div className="bg-[#181816] p-7 text-white sm:p-9"><span className="mb-8 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs"><Sparkles className="size-3 text-[#d9ff53]"/>AI Idea Lab</span><DialogHeader><DialogTitle className="text-3xl font-semibold sm:text-4xl">생각을 프로젝트로.</DialogTitle><DialogDescription className="text-white/55">지금 떠오른 장면이나 감정을 적어보세요.</DialogDescription></DialogHeader></div>{!draft?<div className="p-7 sm:p-9"><label htmlFor="idea" className="text-sm font-semibold">어떤 것을 만들고 싶나요?</label><textarea id="idea" autoFocus value={idea} onChange={e=>setIdea(e.target.value)} placeholder="예: 서울의 밤 풍경을 한글 타이포그래피와 결합한 포스터 시리즈" className="mt-3 min-h-36 w-full resize-none rounded-2xl border bg-[#f6f5f1] p-4 outline-none"/><div className="mt-5 flex justify-end"><Button disabled={!idea.trim()} onClick={generate} className="h-11 rounded-full bg-[#ff5c35] px-5"><WandSparkles/>아이디어 구체화</Button></div></div>:<div className="p-7 sm:p-9"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#ff5c35]">AI concept draft</p><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} className="mt-3 w-full bg-transparent text-2xl font-semibold outline-none"/><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} className="mt-3 min-h-28 w-full resize-none rounded-2xl bg-[#f6f5f1] p-4 text-sm outline-none"/><div className="mt-4 flex flex-wrap gap-2">{draft.tags.map(t=><span key={t} className="rounded-full bg-[#d9ff53] px-3 py-1.5 text-xs font-semibold">#{t}</span>)}</div><div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button variant="outline" onClick={()=>saveProject(false)} className="h-11 rounded-full px-5">초안 저장</Button><Button onClick={()=>saveProject(true)} className="h-11 rounded-full px-5">프로젝트 공개 <ArrowRight/></Button></div></div>}</DialogContent></Dialog>
 </main>
}
function Nav({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:React.ReactNode;children:React.ReactNode}){return <button onClick={onClick} className={`flex items-center justify-center gap-2 rounded-full px-3 py-2 text-sm font-medium [&_svg]:size-4 ${active?'bg-white shadow-sm':'text-black/50'}`}>{icon}{children}</button>}
function Empty({onClick}:{onClick:()=>void}){return <div className="rounded-[28px] border border-dashed border-black/15 py-20 text-center"><Bookmark className="mx-auto mb-4 size-8 text-black/25"/><h2 className="text-xl font-semibold">아직 저장한 콘텐츠가 없어요</h2><p className="mt-2 text-sm text-black/50">마음에 드는 콘텐츠를 모아보세요.</p><Button variant="outline" onClick={onClick} className="mt-5 rounded-full">콘텐츠 발견하기</Button></div>}
